export enum OrganisationTypeEnum {
  EPA = 'EPA',
  EPIC = 'EPIC',
  MINISTERE = 'MINISTERE',
  ENTREPRISE_PRIVEE = 'ENTREPRISE_PRIVEE',
  ENTREPRISE_PUBLIQUE = 'ENTREPRISE_PUBLIQUE',
  GROUPEMENT = 'GROUPEMENT',
}
