export enum RoleNameEnum {
  ADMIN = 'ADMIN',
  SERVICE_CONTRACTANT = 'SERVICE_CONTRACTANT',
  OPERATEUR_ECONOMIQUE = 'OPERATEUR_ECONOMIQUE',
  MEMBRE_COMMISSION = 'MEMBRE_COMMISSION',
  CONTROLEUR = 'CONTROLEUR',
}
